### ISSUE TITLE
Redundant instance data/DRIVEN_AXIS  VariationAxisRecord flag?

### ISSUE THREAD

**Issue by skef** [harfbuzz/boring-expansion-spec#101]
The avar 2 ISO document [says](https://github.com/harfbuzz/boring-expansion-spec/blob/main/iso_docs/m64287-AVAR_OFF_updates.md#simplified-controls-for-parametric-fonts-without-redundant-data):

> The parametric axes are expected to have the Hidden flag set in fvar to discourage (but not block) manual operation.

Thinking about that "but not block" part:

Say I have 4 non-hidden axes driving 6 hidden parametric axes, and I specify all of the former and one of the latter. Reading through the avar 2 algorithm this doesn't seem to be equivalent to *overriding* the parametric axis, because whatever fiddling with the non-hidden axes would do to the hidden one is still happening. 

And there doesn't seem to be a requirement that the default non-hidden axis locations correspond to the default hidden axis locations. Therefore just leaving the former as defaults to be able to adjust the hidden axes the way I want wouldn't necessarily work. However, I suppose a font *could* be constructed this way. 

So for the sake of argument let's assume that the adjustment of hidden axes is left open for such cases. (Maybe there are more.) 

That's all fine, but it leaves me feeling unsettled when considering named instances. In particular: that all named instances, not just quirky ones, will need to supply values for all axes, not just the subset of axes that normally "drive" the other ones. That need can be papered over with tooling but still seems "off". 

So, two questions:

1. Should there be an ALL_AXES instance flag, indicating that the values for every axis should be used, so when it is absent the values for hidden axes will be replaced by those calculated from the values of non-hidden axes? (Omitting the hidden axes in records lacking the flag would be nice but is incompatible with the record array model.)
2. Is "HIDDEN_AXIS" still univocal enough for this purpose, or would there need to be a new axis flag that explicitly addresses this case (e.g. DRIVEN_AXIS)?

**Comment by skef** [comment]
@Lorp I think I may be confused about how all of this works, so let me ask a clarifying question first:   When a font has hidden axes but only"typical" named instances (those which do not attempt to apply unusual/inaccessible values to hidden axes), will the normalized locations for the hidden axes in the instance records always be 0?

**Comment by Lorp** [comment]
Yes that’s right. The usual cases trust avar2 100% to determine the instance’s location, and do not involve user tweaks.

**Comment by skef** [comment]
So in terms of correctness checkers like FontBakery, they can warn based on a simple heuristic of non-0 normalized values on hidden axes in the instance data.

And specifying a named instance in user coordinates just involves mapping the visible axis values through the avar-1-style stuff and adding those values (and 0 for the hidden axes) to the instance records. 

OK, I can see there's no need for a flag for the unusual case now.

**Comment by Lorp** [comment]
A warning about there may turn out to be appropriate, but I think it’s too early to say what people (e.g. Underware) might want to do with avar2. Non-defaults in Named Instance hidden axis records are fine from a spec POV. I suggest we can review in a year or two depending on how people use avar2.

Sorry... I get confused about normalization stage naming, given designspace adds its own mapping at the beginning. Ignoring what happens in designspace documents, fvar uses unnormalized user-axis values everywhere.

**Comment by Lorp** [comment]
An actual use case where a Named Instance may set non-default values on hidden axes is where an axis wants to present as binary on/off but is smooth behind the scenes. For example, the numerous "binary axes" of [Decovar](https://github.com/googlefonts/decovar).

BTW an alternative way of handling this is the "step" mechanism in the [Google Axis Registry](https://fonts.google.com/variablefonts#axis-definitions). The WONK axis has min=0, max=1, step=1 — implying an app should present a binary control. The concept of "step" exists outside of OpenType and OFF, of course, and I would not currently expect non-Google apps to respect "step".

**Comment by skef** [comment]
> fvar uses unnormalized user-axis values everywhere.

Oh, sure enough.

**Comment by skef** [comment]
We may not know how users will want to use avar 2, but we should still be thinking about how tools like FontBakery might be providing advice. "Since one might want to do anything, everything should be considered fine" wouldn't be a great answer.

What I was worried about here was differentiating between common and uncommon cases of named instances. I'm satisfied that the common case is that hidden axes have default values, so that named instances with non-default hidden axis values can be warned about. If that weren't the case, one could argue that some sort of additional flag might be called for.

**Comment by Lorp** [comment]
Sure, that’s fine by me.
