### ISSUE TITLE
[ISO] Mark `CPAL` table optional if there's no colors involved

### ISSUE THREAD

**Issue by behdad** [harfbuzz/boring-expansion-spec#111]
What subject says. A font with `COLR` but without `CPAL` to be allowed.

**Comment by liamquin** [comment]
At the end of the introduction, just before 5.6.11.1 Graphic Compositions, change the last paragraph from:

The COLR table is used in combination with the CPAL table (5.7.12): all color values are specified as entries in color palettes defined in the CPAL table. If the COLR table is present in a font but no CPAL table exists, then the COLR table is ignored.

to

The COLR table may be used in combination with the CPAL table (5.7.12): all color values are specified as entries in color palettes defined in the CPAL table. If the COLR table is present in a font but no CPAL table exists, then the font is monochrome and no additional colors beyond the application foreground (0xFFFF) are available.
