### ISSUE TITLE
[ISO] Bit 7 (CUBIC) is allowed on on-curve points

### ISSUE THREAD

**Issue by behdad** [harfbuzz/boring-expansion-spec#112]
Currently it's disallowed. Explicitly allow it, and mention that some hinting instructions can flip between on-curve and off-curve points, hence this bit might be necessary.

Also expand the 'restrictions' section to say that the number of consecutive cubic off-curves (with wraparound) must be even, both before, and after, running the hinting program.

**Comment by HinTak** [comment]
For on-curve points, the cubic bit is meaningless. On- curve points are end-of-curve points, and therefore can be the joint between a cubic and a quadratic. Is that a cubic or a quadratic point for such a joining point?

I think it might be easier to just ignore the (last) cubic bit if the number is odd. Saying that it is not allowed doesn't mean people won't try - and then demnd for the implemention-specific behaviour to be cast in stone retrospectly as spec.

**Comment by Lorp** [comment]
I’ve been using bit 7 as a "smooth" bit for on-curve points in prototype editing UI. Theoretically it could be beneficial to bring the concept of smoothness from font editors into the binary, allowing certain hinting and variation deltas to be more efficient by only moving one side of an on-curve point; and it sits happily alongside the bit’s use for cubic (_pace_ FLIPPT and related instructions). But behaviour would be tricky to specify. I’m not advocating for it, just mentioning a potential use case.

**Comment by liamquin** [comment]
Edited restrictions:

If the CUBIC flag is non-zero, the corresponding off-curve point belongs to a Cubic Bézier path segment, and all of the following conditions shall be met:
    • The number of consecutive cubic off-curve points within a contour (without wrap-around) is even.
    • Either all the off-curve points between any two on-curve points (with wrap-around) have the CUBIC flag clear, or they all have the CUBIC flag set.
    • The CUBIC flag is allowed on both on-curve and off-curve points. This is because some hinting instructions can flip points between on-curve and off-curve. This specification does not define a meaning for the CUBIC flag on an on-curve point, but it is not an error. 
    • The number of consecutive off-curve points (with wraparound) shall be even, both before and after running the hinting program.

This does not address @Lorp 's comment; it's possible that bit 7 could instead be used to say there are more flags to follow, or that OVERLAP_SIMPLE could be repurposed in GLYF, unless it's still needed somewhere. Closing for now.

**Comment by HinTak** [comment]
I think this is not satisfactory: A series of "Don't do's" (don't don't odd numbers, don't do inconsistent cubic flags on curve segments) aren't useful. People will go ahead and ignore the "don't's" and see what happens, then demand to formalize their preferred outcome. You probably have to define what happens if one does any of those "don't do" things. In particular, the don't do odd numbers is rather awkward - you are relying on font tools/users to check before and after hinting.
