### ISSUE TITLE
[ISO] Add 24bit-GID Paints to `COLR` table

### ISSUE THREAD

**Issue by behdad** [harfbuzz/boring-expansion-spec#115]
Similar to: https://learn.microsoft.com/en-us/typography/opentype/spec/colr#format-10-paintglyph
```
struct PaintGlyph2
{
  uint8 format; // 33
  Offset24 paintOffset;
  uint24 glyphID;
};
```

Similar to https://learn.microsoft.com/en-us/typography/opentype/spec/colr#format-11-paintcolrglyph
```
struct PaintGlyph2
{
  uint8 format; // 34
  uint24 glyphID;
};
```

Search over the text for `PaintGlyph` and `PaintColrGlyph` and update as needed.

@PeterCon I can also add format 3/4 of `ClipBoxList` to extend to 24bit GIDs. Should I do that?

**Comment by behdad** [comment]
> @PeterCon I can also add format 3/4 of `ClipBoxList` to extend to 24bit GIDs. Should I do that?

Nevermind. `BaseGlyphPaintRecord` is still gid16.

**Comment by liamquin** [comment]
Added PaintGlyph2 and PaintColrGlyph2, and updated sections that mention either of them, where it seemed useful or necessary.
