### ISSUE TITLE
[ISO] Add `dmap` table as copy of `cmap`

### ISSUE THREAD

**Issue by behdad** [harfbuzz/boring-expansion-spec#116]
A new "delta-map" table, that is structurally a copy of `cmap` (including the new format 15 addition).

The character-to-glyph lookup algorithm is changed to first look in the `dmap` table (including any variation-selectors). If a match is found, it is used, otherwise the existing algorithm for `cmap` table is used.

cc @PeterCon

**Comment by liamquin** [comment]
(in the draft proposal)

Added normative text at the end of the intro to cmap:

An optional ‘dmap’ table, if present, shall take priority over ‘cmap’—that is, the character-to-glyph lookup shall first look in the ‘dmap’ table (including any variation-selectors). If a match is not found, ‘cmap’ is to be consulted.

However, i'd like to know more about the problems you found with variations (Format 14), @PeterCon if possible

**Comment by Lorp** [comment]
Should the table tag be `DMAP`? @nedley

**Comment by liamquin** [comment]
Yes. DMAP it is.

**Comment by liamquin** [comment]
5.7 DMAP—Delta Map Table

The ‘DMAP’ table is identical to ‘cmap’ except in name.

The character-to-glyph lookup shall first look in ‘DMAP’ (including any variation-selectors). If no match is found, it then proceeds to look in the ‘cmap’ table. This allows individual members of a TTC collection to override or supply parts of the character map.

[i also added a normative paragraph at the end of the intro to cmap to say that DMAP overrides cmap]
