### ISSUE TITLE
[ISO] TTC Header format 1.1 and 2.1

### ISSUE THREAD

**Issue by behdad** [harfbuzz/boring-expansion-spec#117]
Based on https://learn.microsoft.com/en-us/typography/opentype/spec/otff#ttc-header

Add version 1.1, which at the end of version 1.0 header adds:
```
uint32 numFonts2
Offset32 tableDirectoryOffsets2[numFonts2]
```

Add version 2.1, which at the end of version 2.0 header adds the same fields as above.

Spec that if an implementation understands the 1.1 or 2.1 versions, then `tableDirectoryOffsets2` supersedes `tableDirectoryOffsets`.

**Comment by HinTak** [comment]
What about hybrids? As in some member fonts are 1.0/2.0 confirmant. That has implications about the "tableDirectoryOffsets2 supersedes tableDirectoryOffsets." part.

**Comment by behdad** [comment]
> What about hybrids? As in some member fonts are 1.0/2.0 confirmant. That has implications about the "tableDirectoryOffsets2 supersedes tableDirectoryOffsets." part.

A new implementation looks at the 2 version. And old implementation sees the existing fields. That was the whole point.

**Comment by HinTak** [comment]
But an old implementation only understands tableDirectoryOffsets,  so the 'supersedes' statement is null and void.

**Comment by behdad** [comment]
> But an old implementation only understands tableDirectoryOffsets, so the 'supersedes' statement is null and void.

The old implementation conforms to an old spec which doesn't have the 'supersedes' in it.

**Comment by liamquin** [comment]
I’ve added the two fields, and TTHeader 1.1 and 2.1 to the spec (would versions 3 and 4 be safer?) and the wording that an implementation that understands tableDirectoryOffsets2 shall use that and ignore tableDirectoryOffset when both are present, which does not affect older implementations so i think @HinTak your concern is addressed, but please reopen and comment if not.

**Comment by behdad** [comment]
No, versions 3 and 4 defeat the purpose that we want older implementations to see some of the fonts, and new implementation another set of fonts.

**Comment by liamquin** [comment]
Thanks, indeed i had added 1.1 and 2.1, was thinking about a concern someone had raised about older software that didn't check minor versions of tables. But probably such software would predate TTCs anyway.

**Comment by HinTak** [comment]
I think some tools don't even check the major version of the ttc header - I think microsoft dsig signing tool does not (or did not) the last time I looked - microsoft was shipping ttc's with a v1 header having signatures appended. (v1 and v2 differs only at having the signature at the end...). That was only a few years ago, 2015~2018 I checked.
