### ISSUE TITLE
typo in LigatureSet2: ligatureSetOffsets s/be ligatureOffsets

### ISSUE THREAD

**Issue by PeterCon** [harfbuzz/boring-expansion-spec#118]
Typo seen in https://github.com/harfbuzz/boring-expansion-spec/blob/main/iso_docs/WG03-beyond-64k-glyphs-2023-11-20.md:

LigatureSet2* table: All ligatures beginning with the same glyph *

Type | Name | Description
-- | -- | --
uint16 | ligatureCount | Number of Ligature tables
Offset24 | **ligatureSetOffsets**[ligatureCount] | Array of offsets to 24-bit Ligature tables. Offsets are from the beginning of the LigatureSet2 table, ordered by preference

That field name should be **ligatureOffsets**.

**Comment by liamquin** [comment]
Thank you!

Hmm, it's ligatureSetOffsets in the current OFF spec, for LigatureSet table -

Offset16 ligatureSetOffsets[ligatureCount] Array of offsets to Ligature tables. Offsets are from beginning of LigatureSet table, ordered by preference

but i agree, i made the change (for the next draft) and added a note it should be changed in LigatureSet table.

https://learn.microsoft.com/en-us/typography/opentype/spec/gsub has it right :-)

**Comment by PeterConstable** [comment]
I've got to prepare a contribution on sync'ing OFF 5th Edn WC with OT 1.9, so that will show up as I'm doing diffs.

**Comment by liamquin** [comment]
Great news actually, and, extra eyes are helpful. I've been keeping an OFF WD up to date with the proposal too, so contact me privately if it'd be useful to you.
