### ISSUE TITLE
possible typo in BaseCoordFormat 4 (B64K extension for BASE table) in WG03-beyond-64k-glyphs-2024-01e.docx

### ISSUE THREAD

**Issue by mpsuzuki** [harfbuzz/boring-expansion-spec#129]
The BaseCoordFormat4, the B64K extension for BASE table, may have a small typo:
![image](https://github.com/harfbuzz/boring-expansion-spec/assets/2202675/a74c8876-4915-41dc-9d99-5a9b2079c69b)

Maybe the first entry description is expected to be "**format = 4**", instead of "format = 2".

**Comment by liamquin** [comment]
fixed, thanks!
