### ISSUE TITLE
[`glyf`] Variable components

### ISSUE THREAD

**Issue by behdad** [harfbuzz/boring-expansion-spec#42]
To address two limitations:
* Access glyph indices >64k,
* Variable, aka Smart, components ala https://github.com/googlefonts/colr-gradients-spec/issues/277

To be written...

*Update:* The >64k part was moved to https://github.com/be-fonts/boring-expansion-spec/issues/59

**Comment by JeremieHornus** [comment]
I think we can draw a parallel between **variable components** and **non-linear-interpolations**, the first enabling the second.
Enabling two axes of a variable glyph to move together simultaneously, with 2 corner sources (or masters) as quadratic-inverse (see https://github.com/BlackFoundryCom/bezier-interpolation) results in nice bezier interpolation.
Currently the drawback is that one need to set twice the same quadratic-inverse master at each side corners of the glyph's design-space, resulting in waste of size at binary level as well as tedious workflow for designers. But an implementation could take this into account so that there is no need to store them twice.
Note that more complex non-linear interpolations (with 2 intermediate steps istead of only one for quadratic-inverse) can be obtained with 3 cubic-inverse sources and 3 axes.

https://user-images.githubusercontent.com/45566589/144390140-a374b983-50c4-4d6e-8912-90a160a9d4b0.mp4

**Comment by behdad** [comment]
> * Access glyph indices >64k,

Suggesting that we use `numberOfContours` of -2 to mean compositeGlyphs similar to existing compositeGlyphs just with 24bit gid storage instead of 16bit; otherwise same storage format.

**Comment by Lorp** [comment]
The spec says any negative value indicates a composite. I’ve only ever seen -1 in fonts I’ve looked at, but it would be good to do a survey, if anyone has a million fonts, @twardoch?

**Comment by behdad** [comment]
> The spec says any negative value indicates a composite.

Well, it says: "

If the number of contours is greater than or equal to zero, this is a simple glyph. If negative, this is a composite glyph — the value -1 should be used for composite glyphs.
"

**Comment by Lorp** [comment]
In the [Version 1.9](https://docs.microsoft.com/en-us/typography/opentype/spec/glyf#composite-glyph-description) currently on microsoft.com it states:

> If numberOfContours is negative, a composite glyph description is used.  
_Note_: A numberOfContours value of -1 is recommended to indicate a composite glyph.

... which is weaker than “should”.

**Comment by behdad** [comment]
> In the [Version 1.9](https://docs.microsoft.com/en-us/typography/opentype/spec/glyf#composite-glyph-description) currently on microsoft.com it states:
> 
> >

I quoted from other part of the same page :)).

**Comment by Lorp** [comment]
How about we regard it as a bit field (with bit 15 always set, and with all bits set by default), to allow various future glyph encodings or features? To flag 24-bit glyphIds we can unset bit 0, resulting in a value of, er, -2.

**Comment by Lorp** [comment]
Thanks for this nice video, @JeremieHornus.

I assume that any axes used in components are to be “locked” in terms of the user adjusting axes. So in this example, the axes _straight_, _bending*1_, _bending*2_, _pinch*1_ and _pinch*2_ would be locked in position by the component mechanism (and be hidden from the UI), while _weight_ would work as normal. Is that correct?

**Comment by BlackFoundry** [comment]
Yes that's correct, these 'coupled' axes would be hidden from the font user's view, only used when actually instatiating the variable components into another glyph. But even the 'weight' axis could be a local one only used at the glyph level (as opposed to the 'wght' axis of the font).

**Comment by Lorp** [comment]
How does a rasterizer distinguish the two types of axis? (Let’s forget about HOI for a moment.) A flag in fvar?

**Comment by behdad** [comment]
> A flag in fvar?

There's already a "private" flag in fvar.

**Comment by BlackFoundry** [comment]
yeah that's likely enough to set these local axes "private".
With @justvanrossum we made a <VarC> table oprimizing the number of required private axes "recycling" them when needed: https://github.com/BlackFoundryCom/rcjk-tools and https://github.com/BlackFoundryCom/variable-components-spec but this kind of data could well be stored in a <glyf> v2.0 table for example…

**Comment by Lorp** [comment]
The existing HIDDEN_AXIS flag is not sufficient, is it?

I’m assuming these component variation deltas are stored using normal encoding in the gvar table, along with the normal deltas for the user-facing axes. The variation engine needs to know that these axes are never to be adjusted on a font-wide level, because that would lead to a conflict between the font’s designspace location and the component’s designspace location within a composite glyph. Therefore I believe we require a new flag for these axes that declares any axis settings at the font level must be ignored.

**Comment by behdad** [comment]
> The existing HIDDEN_AXIS flag is not sufficient, is it?
> 
> I’m assuming these component variation deltas are stored using normal encoding in the gvar table, along with the normal deltas for the user-facing axes. The variation engine needs to know that these axes are never to be adjusted on a font-wide level (whether by a human or a machine), because that would lead to a conflict between the font’s designspace location and the component’s designspace location within a composite glyph. Therefore I believe we require a new flag for these axes that declares any axis settings at the font level must be ignored.
> 
> EDIT: I see that @justvanrossum @behdad @rsheeter discussed this [here](https://github.com/googlefonts/colr-gradients-spec/issues/277), with @justvanrossum proposing the component’s axis setting simply overrides a global axis setting and some discussion about whether “offsetting” should be allowed (I presume this means that conflicting global and component deltas would be summed).

As per your edit, I don't see the extra need. The component simply overrides the value. It's up to the designer / tooling to ensure that this makes sense. In other words, an old engineering rule holds: Garbage In, Garbage Out.

**Comment by Lorp** [comment]
Consensus is override or sum?

**Comment by behdad** [comment]
> How about we regard numberOfContours as a bit field (with bit 15 always set, and with all bits set by default), to allow various future glyph encodings or features? To flag 24-bit glyphIds we can unset bit 0, resulting in a value of, er, -2.

Forget about numberOfContours for now. componentFlags already has 4 bits available. I'm going to use bit 4 to mean "glyphIDs are 24bit" for now.

**Comment by rsheeter** [comment]
> Consensus is override or sum?

I'm not aware of data to support picking one or the other yet?

**Comment by behdad** [comment]
> > How about we regard numberOfContours as a bit field (with bit 15 always set, and with all bits set by default), to allow various future glyph encodings or features? To flag 24-bit glyphIds we can unset bit 0, resulting in a value of, er, -2.
> 
> Forget about numberOfContours for now. componentFlags already has 4 bits available. I'm going to use (0x2000) to mean "glyphID is 24bit" for now.

I split off the >64k glyph access into https://github.com/be-fonts/boring-expansion-spec/issues/59

**Comment by behdad** [comment]
This is my current thinking:

There will be a new table that holds an ItemVariationStore and possibly an "adjustment list". Then each composite in the glyph table can refer to an adjustment in the adjustment list when invoking a component glyph.

An adjustment in the adjustment list will list a number of axes and variation-store indices for the adjustments to be made to that axis before rendering the glyph invoked.

**Comment by behdad** [comment]
The adjustment-list can use a DeltaSetIndexMap structure, then components need to encode a start offset and number of entries.

**Comment by justvanrossum** [comment]
Our current Variable Component system also requires a fully variable transformation, in function close to the COLRv1 transform/scale/rotate/etc Paints.

**Comment by behdad** [comment]
> Our current Variable Component system also requires a fully variable transformation, in function close to the COLRv1 transform/scale/rotate/etc Paints.

Ah, right. Then I think a new composite glyph format is needed.

**Comment by behdad** [comment]
Okay, then something similar to:
https://github.com/BlackFoundryCom/variable-components-spec

but without the VarStore, and embedded in glyf table as a new glyph composite type with numberOfContours=-2.

**Comment by justvanrossum** [comment]
I'm working on a proposal to store Variable Component data in UFO: https://github.com/BlackFoundryCom/variable-components-in-ufo. I will soon make some test/demo fonts, and will implement it as part of Fontra.

I would like this to be in line with what we expect Variable Components to be able to do in OpenType, so we can use this as a source format.

**Comment by behdad** [comment]
This is complete.
