### ISSUE TITLE
[`CFF`/`CFF2`] Deprecate

### ISSUE THREAD

**Issue by behdad** [harfbuzz/boring-expansion-spec#49]
In favor of `glyf`/`loca`. Cf. https://github.com/be-fonts/boring-expansion-spec/issues/8 https://github.com/be-fonts/boring-expansion-spec/issues/42

**Comment by lrosenthol** [comment]
Deprecate them where?  In Harfbuzz?  If so, that means that you will no longer be able to process the myriad of fonts out there that are CFF/CFF2-based.

What is the rationale for doing so?

**Comment by behdad** [comment]
> Deprecate them where?

In the spec.

> In Harfbuzz? If so, that means that you will no longer be able to process the myriad of fonts out there that are CFF/CFF2-based.

No, we're not going to remove CFF support in HarfBuzz (at least not in the next two decades).

> What is the rationale for doing so?

It is mostly theoretical. To signify that it is unlikely that new developments (like Variable Composites) would happen in CFF2.

You can ignore this issue for all practical purposes.
