### ISSUE TITLE
[WASM Format] Font :: Text Engine API/protocol?

### ISSUE THREAD

**Issue by davelab6** [harfbuzz/boring-expansion-spec#56]
@simoncozens has been working with me and @chrissimpkins and @fonthausen on a "redacted" font (https://github.com/christiannaths/redacted-font) with cap-height semi circular end-caps; Simon will soon publish the script that can derive/generate such a font from any parent font.

However, the customer regularly uses positive letter-spacing, and the way Simon got something working, that creates inter-letter gaps. 

It may be that the font needs to know stuff from the text engine, like how much letter-spacing is being applied, to react to that... Would that be in scope for the "phase 3" expansion spec, giving fonts access to a WASM runtime?

**Comment by justvanrossum** [comment]
A job for the `spac` axis?

https://github.com/Microsoft/OpenTypeDesignVariationAxisTags/blob/master/Proposals/Spacing_Axis/ProposalSummary.md

**Comment by simoncozens** [comment]
The bigger problem is knowing where line breaks are going to happen.

**Comment by behdad** [comment]
More data (eg. whether we're letter-spacing) can be provided to the shaper in the WASM model, yes.

I'm closing this because I'm using issues here to track Boring Expansion proposals. Feel free to open at https://github.com/be-fonts/beyond-emulation-spec
