### ISSUE TITLE
[`hmtx`/`vmtx`] >64k expansion

### ISSUE THREAD

**Issue by behdad** [harfbuzz/boring-expansion-spec#7]
I talk about `hmtx` only. `vmtx` case is similar.

Currently `hmtx` table length is determined by `hhea`/`maxp` in the following way:

- `hhea.metricDataFormat` is required to be 0 for current format;
- `hmtx` is required to be `2 * hhea.numberOfHMetrics + 2 * maxp.numGlyphs` bytes long.

The rest of this issue describes how we relax the second requirement, to allow encoding advance width of arbitrary number of glyphs in `hmtx` table, regardless of the value of `maxp.numGlyphs`.

This is how an advance width is assigned to every glyph index beyond `maxp.numGlyphs`:

- Let `B` be the excess bytes at the end of the `hmtx` table beyond `2 * hhea.numberOfHMetrics + 2 * maxp.numGlyphs` bytes.
- If length of `B` is odd, ignore the last byte of `B`.
- Treat `B` as an array of big-endian uint16 advance-width numbers of glyph indices starting at `maxp.numGlyphs`. For any glyph index that is in range in the font but out of range in this array, use the last item of the array.

**Comment by behdad** [comment]
Speced: https://github.com/harfbuzz/boring-expansion-spec/blob/main/beyond-64k.md
Implemented in HarfBuzz.

**Comment by lrosenthol** [comment]
But this algorithm is completely different from that used by every other font processor in existence today - which means it will break compatibility with all those other tools....and that doesn't seem like a reasonable approach.

**Comment by behdad** [comment]
> But this algorithm is completely different from that used by every other font processor in existence today - which means it will break compatibility with all those other tools....and that doesn't seem like a reasonable approach.

It's *not* completely different. If gid is less than `maxp.numGlyphs` the two algorithms produce the same output. That's backward compatibility right there. Indeed, HarfBuzz uses this algorithm when compiled with experimental-apis feature.

Can you elaborate what problem you see with this?

**Comment by lrosenthol** [comment]
You are assuming that all the processor does is to index into the array - it doesn't copy or evaluate the bytes of the `htmx` otherwise, and I don't believe that to be true.

Certainly, any software doing data validation will fail because the `htmx` block will be larger than expected.  

Why not simply leave the `htmx` (and `vtmx`) alone and create new extended tables for the values beyond the current max?

**Comment by behdad** [comment]
I think an older font sanitizer failing against a newer font format is naturally expected.

> Why not simply leave the `htmx` (and `vtmx`) alone and create new extended tables for the values beyond the current max?

That's possible, but I don't see the problem with what I'm proposing. You can make the same argument about extending *any* table. With your argument we cannot extend anything.
