### ISSUE TITLE
[glyf1] Add mix of component and contours into one glyph

### ISSUE THREAD

**Issue by behdad** [harfbuzz/boring-expansion-spec#75]
That's essential feature.

cc @justvanrossum

**Comment by justvanrossum** [comment]
Yeah, there are definitely cases where this would be beneficial.

**Comment by Lorp** [comment]
It it worth creating analogies for COLRv1’s PaintGlyph and PaintColrGlyph within glyf? I’m thinking about potential uses for transforms of simple glyph data, as well as control of stacking order. We could use a composite flag (bits 4, 13, 14, 15 are currently reserved) to indicate “here comes >0 contours of simple glyph data, optionally transformed”, so allowing arbitrarily ordered contour and component data. Example:

| Layer | What | Simple contours flag | Transformed |
|---|---|---|---|
| 0 | 3 contours | yes | no |
| 1 | 1 component | no | no |
| 2 | 1 component | no | yes |
| 3 | 2 contours | yes | yes |
| 4 | 1 component | no | no |

**Comment by behdad** [comment]
I want to keep this simple...

numContours will work as is right now: -1 for simple Composite glyph, > 0 for simple outlines, and we define 0 for an empty outline. And then any extra bytes at the end of the glyph will be interpreted as VarComposites.  Even if there are four bytes of padding at the end, it will still work since VarComposite record is at least 5 bytes.

**Comment by rsheeter** [comment]
I can see why you'd want this if you have 64k gids but I'm not finding it as obvious why you'd need to mix components and contours if we presume we get big gids. That would lead me to want to get varcs and big gids into the same spec rev, use -2 to mean varco, and call it a day.

I specifically dislike the idea that numContours could be 0 and we have varcs, that will non-obviously break simple tools.

@justvanrossum curious if I'm missing a reason that we specifically need to mix components and contours _in one glyph_?

**Comment by behdad** [comment]
> I can see why you'd want this if you have 64k gids but I'm not finding it as obvious why you'd need to mix components and contours if we presume we get big gids. That would lead me to want to get varcs and big gids into the same spec rev, use -2 to mean varco, and call it a day.

Keeping things as is will definitely simplify implementations.  Or rather, my proposal makes implementations more complex.

**Comment by Lorp** [comment]
Since font editors generally allow contours and components in the same glyph, one motivation may be to preserve such relationships in compiled fonts. It would also happen to make TTF components closer to CFF subroutines (though not allowing subcontours of course).

**Comment by Lorp** [comment]
@behdad:
> … And then any extra bytes at the end of the glyph will be interpreted as VarComposites. Even if there are four bytes of padding at the end, it will still work since VarComposite record is at least 5 bytes.

But what about [this](https://learn.microsoft.com/en-us/typography/opentype/spec/glyf#composite-glyph-description)?

| Mask | Name | Description |
| -- | -- | --
| … |  |  |
| 0x0100 | WE_HAVE_INSTRUCTIONS | Bit 8: Following the last component are instructions for the composite character. |
| … |  |  |

**Comment by behdad** [comment]
> But what about [this](https://learn.microsoft.com/en-us/typography/opentype/spec/glyf#composite-glyph-description)?

Ah yeah. That would be a problem.

I'm leaning towards retracting this.

**Comment by behdad** [comment]
Let's close this for now.
