### ISSUE TITLE
[glyf1] Change rotation storage format

### ISSUE THREAD

**Issue by behdad** [harfbuzz/boring-expansion-spec#77]
I'm hitting a lot of limitations. Because gvar cannot encode 32bit numbers. This is unlike ItemVariationStore, which *can*.

So I think we should change the encoding and use F4DOT12 instead.

cc @justvanrossum

**Comment by behdad** [comment]
Since Skew's are also angles, same applies to them.

**Comment by justvanrossum** [comment]
Yeah, that's what I found as well, when designing/implementing the VarC table. For scale I used three additional flag fields to define the number of integer bits for maximum flexibility. For location values I ended up using F4DOT12 as I ran into cases where location deltas overflowed F2DOT14.

https://github.com/BlackFoundryCom/variable-components-spec#field-formats

**Comment by behdad** [comment]
For location values what I found, compiling GS hanzi, is that the value 2.0 is the only value that overflowed. I encoded it by nudging it down one epsilon.
