### ISSUE TITLE
[`gvar`] >64k expansion

### ISSUE THREAD

**Issue by behdad** [harfbuzz/boring-expansion-spec#85]
Currently `gvar` table encodes a `uint16 glyphCount` that must match "the number of glyphs stored elsewhere in the font."  That field is then used in a subsequent array:

| Type | Name | Description |
| ------- | --------- | ----------------- |
| Offset16 or Offset32 | glyphVariationDataOffsets[glyphCount+1] | Offsets from the start of the GlyphVariationData array to each GlyphVariationData table. |

I propose we deprecate the `glyphCount` field, and make the array size match the number of glyphs stored elsewhere in the font.

This allows us to expand `gvar` without needing to bump to table format 2, which I like to reserve for more extensive table overhaul.

**Comment by behdad** [comment]
Speced: https://github.com/harfbuzz/boring-expansion-spec/blob/main/beyond-64k.md
HarfBuzz NOT implemented.

**Comment by cmyr** [comment]
Fwiw in the course of writing read-fonts I did find cross-table references to be a particular headache, and where possible I would encourage approaches that allow tables to be parsed in isolation.

**Comment by behdad** [comment]
> Fwiw in the course of writing read-fonts I did find cross-table references to be a particular headache, and where possible I would encourage approaches that allow tables to be parsed in isolation.

Yeah that's one of the unfortunate points of this approach...

**Comment by behdad** [comment]
Implemented in HarfBuzz.

**Comment by behdad** [comment]
Implemented in HarfBuzz.
